-- Generated by Oracle SQL Developer Data Modeler 24.3.1.347.1153
--   at:        2026-01-09 23:39:06 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE attachment (
    file_hash            RAW(32) NOT NULL,
    file_address         VARCHAR2(250) NOT NULL,
    sign_file            RAW(64) NOT NULL,
    user_info_public_key RAW(33) NOT NULL
);

ALTER TABLE attachment
    ADD CONSTRAINT attachment_pk PRIMARY KEY ( file_hash,
                                               file_address,
                                               user_info_public_key );

CREATE TABLE member (
    commit_array_index        INTEGER,
    commit_hash               RAW(32),
    commit_previous_entry     RAW(32),
    commit_poll               RAW(32),
    sign_commit               RAW(64),
    poll_user_info_public_key RAW(33) NOT NULL,
    user_info_public_key      RAW(33) NOT NULL,
    poll_info_name            VARCHAR2(100) NOT NULL
);

ALTER TABLE member
    ADD CONSTRAINT member_pk PRIMARY KEY ( user_info_public_key,
                                           poll_user_info_public_key,
                                           poll_info_name );

CREATE TABLE "option" (
    name                      VARCHAR2(50) NOT NULL,
    min_value                 RAW(32),
    max_value                 RAW(32),
    poll_user_info_public_key RAW(33) NOT NULL,
    poll_info_name            VARCHAR2(100) NOT NULL
);

ALTER TABLE "option"
    ADD CONSTRAINT option_pk PRIMARY KEY ( name,
                                           poll_user_info_public_key,
                                           poll_info_name );

CREATE TABLE poll (
    info_name            VARCHAR2(100) NOT NULL,
    info_poll_start      TIMESTAMP WITH LOCAL TIME ZONE,
    info_poll_end        TIMESTAMP WITH TIME ZONE,
    sign_poll            RAW(64),
    user_info_public_key RAW(33) NOT NULL
);

ALTER TABLE poll ADD CONSTRAINT poll_pk PRIMARY KEY ( user_info_public_key,
                                                      info_name );

CREATE TABLE relation_1 (
    attachment_file_hash       RAW(32) NOT NULL,
    attachment_file_address    VARCHAR2(250) NOT NULL,
    attachment_info_public_key RAW(33) NOT NULL,
    poll_info_public_key       RAW(33) NOT NULL,
    poll_info_name             VARCHAR2(100) NOT NULL
);

ALTER TABLE relation_1
    ADD CONSTRAINT relation_1_pk
        PRIMARY KEY ( attachment_file_hash,
                      attachment_file_address,
                      attachment_info_public_key,
                      poll_info_public_key,
                      poll_info_name );

CREATE TABLE "user" (
    info_public_key      RAW(33) NOT NULL,
    info_permissions     CHAR(1) NOT NULL,
    info_name            VARCHAR2(25) NOT NULL,
    author_sign_info     RAW(64),
    user_info_public_key RAW(33)
);

ALTER TABLE "user" ADD CONSTRAINT user_pk PRIMARY KEY ( info_public_key );

CREATE TABLE vote (
    vote_value                RAW(32) NOT NULL,
    vote_entries_root         RAW(32) NOT NULL,
    vote_nullifier            RAW(32) NOT NULL,
    vote_previous_vote        RAW(32),
    proof_vote                CLOB NOT NULL,
    poll_user_info_public_key RAW(33) NOT NULL,
    poll_info_name            VARCHAR2(100) NOT NULL,
    option_name               VARCHAR2(50),
    option_info_public_key    RAW(33),
    option_info_name          VARCHAR2(100)
);

ALTER TABLE vote
    ADD CONSTRAINT vote_pk PRIMARY KEY ( vote_nullifier,
                                         poll_user_info_public_key,
                                         poll_info_name );

ALTER TABLE attachment
    ADD CONSTRAINT attachment_user_fk FOREIGN KEY ( user_info_public_key )
        REFERENCES "user" ( info_public_key );

ALTER TABLE member
    ADD CONSTRAINT member_poll_fk
        FOREIGN KEY ( poll_user_info_public_key,
                      poll_info_name )
            REFERENCES poll ( user_info_public_key,
                              info_name );

ALTER TABLE member
    ADD CONSTRAINT member_user_fk FOREIGN KEY ( user_info_public_key )
        REFERENCES "user" ( info_public_key );

ALTER TABLE "option"
    ADD CONSTRAINT option_poll_fk
        FOREIGN KEY ( poll_user_info_public_key,
                      poll_info_name )
            REFERENCES poll ( user_info_public_key,
                              info_name );

ALTER TABLE poll
    ADD CONSTRAINT poll_user_fk FOREIGN KEY ( user_info_public_key )
        REFERENCES "user" ( info_public_key );

ALTER TABLE relation_1
    ADD CONSTRAINT relation_1_attachment_fk
        FOREIGN KEY ( attachment_file_hash,
                      attachment_file_address,
                      attachment_info_public_key )
            REFERENCES attachment ( file_hash,
                                    file_address,
                                    user_info_public_key );

ALTER TABLE relation_1
    ADD CONSTRAINT relation_1_poll_fk
        FOREIGN KEY ( poll_info_public_key,
                      poll_info_name )
            REFERENCES poll ( user_info_public_key,
                              info_name );

ALTER TABLE "user"
    ADD CONSTRAINT user_user_fk FOREIGN KEY ( user_info_public_key )
        REFERENCES "user" ( info_public_key );

ALTER TABLE vote
    ADD CONSTRAINT vote_option_fk
        FOREIGN KEY ( option_name,
                      option_info_public_key,
                      option_info_name )
            REFERENCES "option" ( name,
                                  poll_user_info_public_key,
                                  poll_info_name );

ALTER TABLE vote
    ADD CONSTRAINT vote_poll_fk
        FOREIGN KEY ( poll_user_info_public_key,
                      poll_info_name )
            REFERENCES poll ( user_info_public_key,
                              info_name );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             17
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
